//! Claude Code adapter. Verified on this machine against claude 2.1.214
//! (fixtures live in this crate's tests; re-verify on version change):
//! - `--session-id <uuid>` : caller-assigned native session id -> EXACT resume id known at launch.
//! - `-r, --resume [value]` : resume by session id.
//! - `-c, --continue`       : resume most recent in cwd (precision = latest).
//! - `--permission-mode <mode>` : native UI modes only; NEVER default to bypass.
//! - `--dangerously-skip-permissions` : bypass flag, ONLY on explicit user opt-in (preset=bypass).
//! - Hooks: settings.json `hooks` (e.g. PreToolUse, UserPromptSubmit, Notification, Stop,
//!   SessionStart/SessionEnd). Integration must be PER-INVOCATION and reversible —
//!   verify `--settings <file>` exists in this version before use; if absent, hooks
//!   degrade (HookStatus::Degraded) and we never touch ~/.claude/settings.json.
//! - Hook commands append one JSON line to ctx.hook_events_path. The command line
//!   is generated by us; it must embed the event name and quote paths safely.

use super::{AgentAdapter, LaunchContext, LaunchPlan, ResumeContext};
use crate::error::{CoreError, Result};
use crate::models::*;
use std::path::{Path, PathBuf};

pub struct ClaudeAdapter;

/// Hook events registered in the per-session settings file.
const HOOK_EVENTS: &[&str] = &[
    "PreToolUse",
    "UserPromptSubmit",
    "Notification",
    "Stop",
    "SessionStart",
    "SessionEnd",
];

/// Escape a string for embedding inside a double-quoted shell word.
fn shell_dq_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`")
}

/// One hook command: append a single JSON line carrying the event name, our
/// AgentPort session id and the hook payload to `events_path`.
///
/// Assumption (documented in Claude Code's hook docs): hook stdin is ONE
/// single-line JSON object, so `read` captures the whole payload and
/// interpolating it as `$l` yields valid JSON (`"data":{...}`). If a future
/// version ever sends multi-line stdin, only the first line is recorded —
/// hooks degrade, they never corrupt the events file with invalid JSON...
/// except truncated JSON, which the events reader must tolerate per line.
fn hook_command(event: &str, session_id: &str, events_path: &str) -> String {
    format!(
        "sh -c 'IFS= read -r l; printf \"%s\\n\" \"{{\\\"event\\\":\\\"{event}\\\",\\\"session_id\\\":\\\"{sid}\\\",\\\"data\\\":$l}}\" >> \"{path}\"'",
        sid = shell_dq_escape(session_id),
        path = shell_dq_escape(events_path),
    )
}

/// Contents of the per-session `--settings` file registering all hook events.
/// Written by the caller with mode 0600 (see LaunchPlan.helper_files).
pub(crate) fn settings_json(session_id: &str, events_path: &str) -> String {
    let mut hooks = serde_json::Map::new();
    for event in HOOK_EVENTS {
        let cmd = hook_command(event, session_id, events_path);
        let mut entry = serde_json::json!({
            "hooks": [{ "type": "command", "command": cmd }]
        });
        // matcher "" = all tools; only meaningful for tool events.
        if *event == "PreToolUse" {
            entry["matcher"] = serde_json::json!("");
        }
        hooks.insert(event.to_string(), serde_json::json!([entry]));
    }
    serde_json::to_string_pretty(&serde_json::json!({ "hooks": hooks }))
        .unwrap_or_else(|_| "{}".into())
}

impl AgentAdapter for ClaudeAdapter {
    fn agent_type(&self) -> AgentType {
        AgentType::Claude
    }

    fn parse_capabilities(
        &self,
        exe: &Path,
        version_out: &str,
        help_out: &str,
    ) -> Result<AdapterInstall> {
        let flags = super::extract_flags(help_out);
        let has = |f: &str| flags.iter().any(|x| x == f);
        // exact resume needs a caller-assigned id AND a resume-by-id flag.
        let exact_resume = has("session-id") && has("resume");
        let hook_status = if has("settings") {
            HookStatus::Supported
        } else {
            HookStatus::Degraded
        };
        Ok(AdapterInstall {
            agent_type: AgentType::Claude,
            executable_path: exe.to_string_lossy().into_owned(),
            version_text: super::normalize_version(version_out),
            capability_hash: super::capability::capability_hash(version_out, help_out),
            exact_resume,
            hook_status,
            approval_model: AgentType::Claude.approval_model(),
            default_transport: AgentType::Claude.default_transport(),
            probed_at: chrono::Utc::now(),
            candidates: vec![],
            flags,
        })
    }

    fn build_launch(&self, ctx: &LaunchContext) -> Result<LaunchPlan> {
        let install = &ctx.install;
        let exe = install.executable_path.clone();
        let mut argv = vec![exe];
        let mut notes: Vec<String> = Vec::new();
        let mut helper_files = vec![];

        // Per-invocation hook injection via --settings (never global config).
        let hook_status = if super::has_flag(install, "settings") {
            let file = format!("{}/claude-settings.json", ctx.session_dir);
            helper_files.push((
                file.clone(),
                settings_json(&ctx.session_id, &ctx.hook_events_path),
            ));
            argv.push("--settings".into());
            argv.push(file);
            HookStatus::Supported
        } else {
            notes.push("该版本无 --settings，hook 降级为 PTY 启发式".into());
            HookStatus::Degraded
        };

        // Caller-assigned native session id -> exact resume.
        let (assigned, resume_precision) = if super::has_flag(install, "session-id") {
            let uuid = crate::ids::new_uuid();
            argv.push("--session-id".into());
            argv.push(uuid.clone());
            (Some(uuid), ResumePrecision::Exact)
        } else {
            notes.push("该版本无 --session-id，无法指定原生会话 ID，仅支持恢复最近会话".into());
            (None, ResumePrecision::Latest)
        };

        argv.extend(ctx.preset.args.clone());
        argv.extend(super::permission_argv(
            AgentType::Claude,
            ctx.preset.permission_mode,
            install,
        )?);

        Ok(LaunchPlan {
            argv,
            env: vec![],
            assigned_agent_session_id: assigned,
            resume_precision,
            hook_status,
            transport: ctx.transport,
            helper_files,
            notes,
        })
    }

    fn build_resume(&self, ctx: &ResumeContext) -> Result<LaunchPlan> {
        let install = &ctx.install;
        let exe = || install.executable_path.clone();
        let mut argv = vec![exe()];
        let mut notes = Vec::new();

        let resume_precision = match &ctx.agent_session_id {
            Some(id) => {
                if !super::has_flag(install, "resume") {
                    return Err(CoreError::Blocked(
                        "该版本 claude 无 --resume，无法精确恢复会话".into(),
                    ));
                }
                argv.push("--resume".into());
                argv.push(id.clone());
                ResumePrecision::Exact
            }
            None => {
                if !super::has_flag(install, "continue") {
                    return Err(CoreError::Blocked(
                        "无原生会话 ID 且该版本 claude 无 --continue，无法恢复".into(),
                    ));
                }
                argv.push("--continue".into());
                notes.push("无原生会话 ID，仅支持恢复最近会话".into());
                ResumePrecision::Latest
            }
        };
        argv.extend(ctx.preset.args.clone());
        argv.extend(super::permission_argv(
            AgentType::Claude,
            ctx.preset.permission_mode,
            install,
        )?);

        Ok(LaunchPlan {
            argv,
            env: vec![],
            assigned_agent_session_id: None,
            resume_precision,
            hook_status: install.hook_status,
            transport: ctx.transport,
            helper_files: vec![],
            notes,
        })
    }

    fn build_resume_checked(&self, ctx: &ResumeContext) -> Result<LaunchPlan> {
        self.build_resume_with(ctx, &claude_config_dir())
    }
}

/// Base of claude's config/transcript storage. CLAUDE_CONFIG_DIR relocates
/// the whole ~/.claude tree; conversations live under <base>/projects.
fn claude_config_dir() -> PathBuf {
    if let Some(dir) = std::env::var_os("CLAUDE_CONFIG_DIR") {
        if !dir.is_empty() {
            return PathBuf::from(dir);
        }
    }
    PathBuf::from(std::env::var_os("HOME").unwrap_or_default()).join(".claude")
}

/// Claude stores each conversation at projects/<slug(cwd)>/<id>.jsonl, where
/// the slug replaces every non-alphanumeric character with '-'.
fn transcript_path(config_dir: &Path, cwd: &str, native_id: &str) -> PathBuf {
    let slug: String = cwd
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    config_dir
        .join("projects")
        .join(slug)
        .join(format!("{native_id}.jsonl"))
}

/// Claude writes transcripts lazily on the first message, so an idle first
/// run leaves nothing on disk: resume-by-id would exit 1 with
/// "No conversation found with session ID".
fn resume_transcript_exists(config_dir: &Path, cwd: &str, native_id: &str) -> bool {
    transcript_path(config_dir, cwd, native_id).is_file()
}

impl ClaudeAdapter {
    fn build_resume_with(&self, ctx: &ResumeContext, config_dir: &Path) -> Result<LaunchPlan> {
        if let Some(id) = &ctx.agent_session_id {
            if super::has_flag(&ctx.install, "resume")
                && !resume_transcript_exists(config_dir, &ctx.cwd, id)
            {
                // The recorded conversation was never persisted (or is gone).
                // Start a fresh conversation with a newly assigned native id
                // instead of failing the whole restart.
                let mut plan = self.build_launch(&LaunchContext {
                    install: ctx.install.clone(),
                    preset: ctx.preset.clone(),
                    cwd: ctx.cwd.clone(),
                    session_id: ctx.session_id.clone(),
                    hook_events_path: ctx.hook_events_path.clone(),
                    session_dir: ctx.session_dir.clone(),
                    transport: ctx.transport,
                })?;
                plan.notes.push(
                    "原会话没有可恢复的对话记录（首轮可能未产生消息），已按新会话启动".into(),
                );
                return Ok(plan);
            }
        }
        self.build_resume(ctx)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::test_fixtures as fx;

    fn real_install() -> AdapterInstall {
        ClaudeAdapter
            .parse_capabilities(
                Path::new("/Users/w/.local/bin/claude"),
                &fx::read_fixture("claude-version.txt"),
                &fx::read_fixture("claude-help.txt"),
            )
            .unwrap()
    }

    #[test]
    fn parse_real_fixtures() {
        let i = real_install();
        assert_eq!(i.version_text, "2.1.214 (Claude Code)");
        for f in [
            "session-id",
            "resume",
            "continue",
            "settings",
            "permission-mode",
            "dangerously-skip-permissions",
        ] {
            assert!(i.flags.iter().any(|x| x == f), "missing flag {f}");
        }
        assert!(i.exact_resume);
        assert_eq!(i.hook_status, HookStatus::Supported);
        assert!(i.version_text.len() <= 200);
    }

    #[test]
    fn parse_unknown_future_version_degrades() {
        // 合成的“未来版本” help：去掉 session-id 与 settings
        let help = fx::read_fixture("claude-help.txt")
            .replace("--session-id", "--sess-id")
            .replace("--settings", "--cfg");
        let i = ClaudeAdapter
            .parse_capabilities(Path::new("/x/claude"), "9.9.9", &help)
            .unwrap();
        assert!(!i.exact_resume, "缺 session-id 必须降级 exact_resume");
        assert_eq!(
            i.hook_status,
            HookStatus::Degraded,
            "缺 settings 必须降级 hook"
        );
    }

    #[test]
    fn settings_json_snapshot() {
        let json = settings_json("ses_abc", "/tmp/work dir/.agentport/hook-events.jsonl");
        // 必须是合法 JSON
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        let hooks = v["hooks"].as_object().unwrap();
        for ev in [
            "PreToolUse",
            "UserPromptSubmit",
            "Notification",
            "Stop",
            "SessionStart",
            "SessionEnd",
        ] {
            assert!(hooks.contains_key(ev), "missing hook {ev}");
            let cmd = hooks[ev][0]["hooks"][0]["command"].as_str().unwrap();
            // 每条命令带事件名，且事件名出现在追加的 JSON 行模板里
            assert!(
                cmd.contains(&format!("\\\"event\\\":\\\"{ev}\\\"")),
                "cmd for {ev}: {cmd}"
            );
            // 路径含空格：必须被双引号包住
            assert!(
                cmd.contains(">> \"/tmp/work dir/.agentport/hook-events.jsonl\""),
                "path not quoted: {cmd}"
            );
            // session id 嵌入
            assert!(cmd.contains("ses_abc"));
        }
    }

    #[test]
    fn settings_json_escapes_dollar_and_quote() {
        let json = settings_json("ses_abc", "/tmp/evil\"$HOME/hook-events.jsonl");
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        let cmd = v["hooks"]["Stop"][0]["hooks"][0]["command"]
            .as_str()
            .unwrap();
        assert!(
            cmd.contains("\\\"\\$HOME"),
            "shell metachars not escaped: {cmd}"
        );
    }

    #[test]
    fn build_launch_argv_order_and_helper_files() {
        let mut ctx = fx::launch_ctx(
            AgentType::Claude,
            &["settings", "session-id", "permission-mode"],
            PermissionMode::Auto,
        );
        ctx.install.executable_path = "/usr/local/bin/claude".into();
        ctx.preset.args = vec!["--model".into(), "sonnet".into()];
        let plan = ClaudeAdapter.build_launch(&ctx).unwrap();

        assert_eq!(plan.argv[0], "/usr/local/bin/claude");
        assert_eq!(plan.argv[1], "--settings");
        assert_eq!(plan.argv[2], "/tmp/work/.agentport/claude-settings.json");
        assert_eq!(plan.argv[3], "--session-id");
        let uuid = &plan.argv[4];
        uuid::Uuid::parse_str(uuid).expect("assigned id must be uuid");
        assert_eq!(
            plan.argv[5..],
            ["--model", "sonnet", "--permission-mode", "acceptEdits"]
        );
        assert_eq!(
            plan.assigned_agent_session_id.as_deref(),
            Some(uuid.as_str())
        );
        assert_eq!(plan.resume_precision, ResumePrecision::Exact);
        assert_eq!(plan.hook_status, HookStatus::Supported);

        // helper_files: 单个 settings 文件，内容即 settings_json 快照
        assert_eq!(plan.helper_files.len(), 1);
        assert_eq!(
            plan.helper_files[0].0,
            "/tmp/work/.agentport/claude-settings.json"
        );
        let v: serde_json::Value = serde_json::from_str(&plan.helper_files[0].1).unwrap();
        assert_eq!(v["hooks"].as_object().unwrap().len(), 6);
    }

    #[test]
    fn build_launch_degrades_without_flags() {
        let ctx = fx::launch_ctx(AgentType::Claude, &[], PermissionMode::Native);
        let plan = ClaudeAdapter.build_launch(&ctx).unwrap();
        assert_eq!(plan.assigned_agent_session_id, None);
        assert_eq!(plan.resume_precision, ResumePrecision::Latest);
        assert_eq!(plan.hook_status, HookStatus::Degraded);
        assert!(plan.helper_files.is_empty());
        assert!(!plan.notes.is_empty());
        assert!(!plan
            .argv
            .iter()
            .any(|a| a == "--settings" || a == "--session-id"));
    }

    #[test]
    fn build_resume_exact_latest_blocked() {
        // exact
        let ctx = fx::resume_ctx(AgentType::Claude, &["resume", "continue"], Some("uuid-1"));
        let plan = ClaudeAdapter.build_resume(&ctx).unwrap();
        assert_eq!(plan.resume_precision, ResumePrecision::Exact);
        assert_eq!(plan.argv[1..], ["--resume", "uuid-1"]);
        // latest
        let ctx = fx::resume_ctx(AgentType::Claude, &["resume", "continue"], None);
        let plan = ClaudeAdapter.build_resume(&ctx).unwrap();
        assert_eq!(plan.resume_precision, ResumePrecision::Latest);
        assert_eq!(plan.argv[1..], ["--continue"]);
        assert!(plan.notes.iter().any(|n| n.contains("最近会话")));
        // blocked: 有 id 但无 resume flag
        let ctx = fx::resume_ctx(AgentType::Claude, &["continue"], Some("uuid-1"));
        assert!(matches!(
            ClaudeAdapter.build_resume(&ctx),
            Err(crate::error::CoreError::Blocked(_))
        ));
    }

    #[test]
    fn transcript_path_slugifies_cwd() {
        let p = transcript_path(
            Path::new("/cfg"),
            "/Users/w/Library/Application Support/AgentPort/worktrees/skilldock/fixbug",
            "abc-123",
        );
        assert_eq!(
            p,
            Path::new(
                "/cfg/projects/-Users-w-Library-Application-Support-AgentPort-worktrees-skilldock-fixbug/abc-123.jsonl"
            )
        );
    }

    #[test]
    fn checked_resume_falls_back_to_fresh_when_transcript_missing() {
        let dir = tempfile::tempdir().unwrap();
        let ctx = fx::resume_ctx(
            AgentType::Claude,
            &["resume", "continue", "session-id", "settings"],
            Some("dead-id"),
        );
        let plan = ClaudeAdapter.build_resume_with(&ctx, dir.path()).unwrap();
        // Fresh conversation: no --resume, newly assigned id, explanatory note.
        assert!(!plan.argv.iter().any(|a| a == "--resume"));
        let pos = plan
            .argv
            .iter()
            .position(|a| a == "--session-id")
            .expect("fresh plan assigns a native id");
        assert_ne!(plan.argv[pos + 1], "dead-id");
        assert_eq!(
            plan.assigned_agent_session_id.as_deref(),
            Some(plan.argv[pos + 1].as_str())
        );
        assert_eq!(plan.resume_precision, ResumePrecision::Exact);
        assert!(plan.notes.iter().any(|n| n.contains("新会话启动")));
    }

    #[test]
    fn checked_resume_keeps_exact_when_transcript_exists() {
        let dir = tempfile::tempdir().unwrap();
        let ctx = fx::resume_ctx(
            AgentType::Claude,
            &["resume", "continue", "session-id", "settings"],
            Some("live-id"),
        );
        let transcript = transcript_path(dir.path(), &ctx.cwd, "live-id");
        std::fs::create_dir_all(transcript.parent().unwrap()).unwrap();
        std::fs::write(&transcript, "{}\n").unwrap();
        let plan = ClaudeAdapter.build_resume_with(&ctx, dir.path()).unwrap();
        let pos = plan
            .argv
            .iter()
            .position(|a| a == "--resume")
            .expect("exact resume keeps --resume");
        assert_eq!(plan.argv[pos + 1], "live-id");
        assert_eq!(plan.resume_precision, ResumePrecision::Exact);
    }
}
