[package]
name = "tauri-plugin-image-picker"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-image-picker"
license = "GPL-3.0-only"

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
